### ISSUE TITLE
Subclassing ReduxAction reduce must not return FutureOr<St?>

### ISSUE THREAD

**Issue by saibotma** [marcglasberg/async_redux#123]
Unfortunately, an implementation like the following does not work, because `reduce` must not return `FutureOr`.
How are we supposed to handle this? 

```dart
abstract class LoginAction extends BaseAction {
  late final RootState Function(LoginState) copyParentState =
      (childState) => state.copyWith(loginState: childState);

  LoginState get loginState => state.loginState;

  FutureOr<LoginState?> reduceLoginState();

  @override
  FutureOr<RootState?> reduce() {
    final childState = reduceLoginState();
    if (childState is Future<LoginState?>) {
      return childState.then((_childState) {
        return _childState == null ? null : copyParentState(_childState);
      });
    } else {
      return (childState == null) ? null : copyParentState(childState);
    }
  }
}
```

The documentation completely avoids this case by always returning `Future` in that subclassed action. However, doesn't this mean that the action will never be executed in sync? And also the check `if (todoState is Future)` is useless, because `reduceTodoState` is declared as returning `TodoState`.

```dart
abstract class TodoAction extends BaseAction {
  
  TodoState reduceTodoState();
      
  @override
  Future<AppState> reduce() {
    Future<TodoState> todoState = reduceTodoState();
    if (todoState is Future) return todoState.then((_todoState) => state.copy(todoState: _todoState));   
    else return (todoState == null) ? null : state.copy(todoState: todoState);
  }
}
```

**Comment by marcglasberg** [comment]
Creating multiple abstract Action subclasses (having a `SubAction` that extends `BaseAction`) seemed like a good idea when I was first developing AsyncRedux. It does seem nice in paper, right? But then in real life it ends up being more work than it's worth it. I have actually stopped doing this a long time ago. Why? Because in LoginAction you can easily change LoginState, but if you also want to change some OtherState in the same action you cannot. 

I kept this idea in the documentation in case someone else would find it useful, but you have just demonstrated this is actually REALLY not a good idea anymore. The problem is that, when I wrote that documentation, AsyncRedux worked in a different way that would allow you to return a `Future<RootState>` or `RootState`, and it would use the runtime-type of that returned value. But that has since changed and now it will consider the compile-time type of the `reduce` method itself, meaning you now have to choose one or the other. I won't go into the detail why that was changed (it helped improving AsyncRedux in a number of ways, but that's unimportant for this discussion).

I apologize if I made you spend time trying something that doesn't work well. I will remove that idea from the documentation.

Instead of having multiple abstract Action subclasses I'd recommend you create just a single one, and add your getter helpers to it. For example, your `BaseAction` can have all the getters to help you get the substates (or even substates of substates). For example:

```
class BaseAction extends ReduxAction<RootState> {

   // Getter helpers:
   LoginState get loginState => state.loginState;
   OtherState get otherState => state.otherState;
}
```

You can use it like this:

```
return state.copy(loginState: loginState.copy(id: myId));
```

Also note that `LoginState` could have a specialized `copyState` method (besides the regular `copy` method), like so:

```
class LoginState {

   LoginState copy({String? id}) => LoginState(id: id ?? this.id);

   RootState copyState({String? id}) => state.copy(loginState: copy(id: id));
}
```

You can use it like this:

```
return loginState.copyState(id: myId));
```

**Comment by saibotma** [comment]
Thanks for the detailed explanation. This clarifies things for me.

I opted to use the copyState approach, however I did it a bit differently as you did. Just in case anyone is interested.

This is an action subclass in my implementation:
```
abstract class LoginAction extends RootAction {
  RootState copyState(LoginState childState) {
    return state.copyWith(loginState: childState);
  }
}
```
