### ISSUE TITLE
Store/waitCondition access in 22+

### ISSUE THREAD

**Issue by kuhnroyal** [marcglasberg/async_redux#152]
There are some awesome changes in the latest version(s), really like that!

I have built a wrapper around `StoreConnector` that waits until a `waitCondition` is met before doing its magic.

I am now missing a way to access `store.waitCondition`.
My wrapper also manually calls the `OnInitCallback` which requires the `store` as parameter and I also have no more access to this.

1. Is there a way to get the store?
2. Is there a way to get the state without listening? Basically something like `context.getState(listen: false)`?
3. Can I access the `waitCondition` function without having a store?

Thanks!

**Comment by marcglasberg** [comment]
I'm glad you like the new features!

Please upgrade to version 22.4.4. 

From `StoreProvider`, `VmFactory` and `ReduxAction` you should now have access to:

* `state`
* `dispatch`
* `dispatchSync`
* `dispatchAndWait`
* `waitCondition`
* `waitAllActions`
* `isWaiting`
* `isFailed`
* `exceptionFor`
* `clearExceptionFor`.

Now `StoreProvider.state` has a `notify` parameter for you to get the state without rebuilding (and so do `isWaiting`, `isFailed`, `exceptionFor` and `clearExceptionFor`).

You can get the store with `backdoorInheritedWidget` but that's only for advanced use cases, like yours. The reason it's not exposed simply as `store` is because people could use it to get the `state`, and it wouldn't rebuild when the state changes. That's almost always the wrong way to get the state.

**Comment by kuhnroyal** [comment]
Thanks I checked and seem to be able to adjust everything now!
