### ISSUE TITLE
AsyncRedux to Redux slices migration (React web) + Equatable for state objects

### ISSUE THREAD

**Issue by sofasurfa** [marcglasberg/async_redux#165]
## Not an issue but 2 questions regarding: migrating from AsyncRedux to Slices (for a future React web app) + Equatable use for State objects

We decided to go with this library instead of `flutter_redux` last minute due to less boilerplate (like modern Redux with slices).

**Question 1**: Looks like there's no need for hashCodes/equals operator in `Vm` just use `super(equals: [counter, etc..]);` 👍 But looks like we do need them in State objects (AppState/UserState,etc) right? **Is it safe to use `Equatable` instead?**

**Question 2**:  Because this library looks very similar to RTK’s `createSlice`: if our team goes with **AsyncRedux** do you think it will quite easy to migrate to slices if we decide to build a React website in the future? If so, what are some of the notable pitfalls people should look out for while migrating. Just asking, because some of you might have already done so, or vice-versa… Thanks in advance. +Hope questions like these will get this library more attention on the search that it deserves :) 

**Question 3 (bonus question)**: So do VMs allow for "finer" control on what the `StoreConnector` listens to before updating? So we can just say.. at the top of our app have one `StoreConnector` listen to a VM with `state.authState.isLoggedIn` and `state.appState.appTheme`? Which would be nicer than having 2 `StoreConnector` listening to these specific state fields.

Background story: We started with BLOC/Cubit pattern, splitting our stores (seems to be the new trend now), just to realise that having one central store is the way to go! As you will end up having a store/bloc needing access to another at some point leading to dependency injection or BlocProvider tree order manipulation circus.. Redux makes life much easier 🥰

**Comment by sofasurfa** [comment]
@marcglasberg

**Comment by marcglasberg** [comment]
1. Actually There **is** a need for the equals operator in `Vm`. It's just that when you provide the `equals: [counter, ...]` parameter, it works like Equatable to implement the equals operator automatically. However, you can implement the equals operator yourself instead of using the `equals: ..` parameter if you prefer; both approaches work. The equals operator is   necessary because the framework compares the previous `Vm` with the current `Vm` to decide whether to rebuild the widget. Without a proper equals implementation, it defaults to `Object`’s equals method, which treats all instances as unequal, causing the widget to rebuild every time the state changes. State objects (like `AppState` or `UserState`) also need the equals operator for the same reason: to determine if they’ve changed and whether a rebuild is required. Using Equatable or any other method to   implement equals for the state objects is perfectly fine.

2. Migrating from AsyncRedux to RTK is probably not "quite easy," but it’s certainly easier than migrating from other Flutter state management solutions. However, keep in mind that AsyncRedux offers many features that RTK doesn’t. For instance, AsyncRedux supports asynchronous actions, error handling (e.g., automatic dialogs or toasts for action errors), actions dispatching actions, state persistence, internet connectivity checks, retry mechanisms, events, and more. In RTK, you’d have to implement many of these manually. Alternatively, why not directly use **AsyncRedux for React**? Check out 
https://asyncredux.com](https://asyncredux.com) for details. The React version of AsyncRedux is newer, and incorporates lessons learned from the Flutter version, making it even better. That said, I got instant pushback over using the "Redux" name in React, so I’m not yet promoting the package. I will be renaming it to **KISS State Management** and launching in 2025. However, you can right now use AsyncRedux for React, and just replace it with the KISS package when it’s available.

4. Yes, that’s exactly right. `Vm` serves three purposes:
    - **Optimized rebuilding**: It isolates the part of the state needed by a widget, so only that part triggers a rebuild when it changes.
    - **Separation of concerns**: It keeps state selection logic out of the widget code. Widgets only receive the state they need through their constructors, without knowing the state’s structure.
    - **Simplified testing**: With `Vm`, you can test widgets by directly passing parameters without setting up a full store.

   In practice, I often access the state directly in widgets using `context.state` during development. Later, I refactor to use `Vm` only for widgets with complex state access, optimization needs (widgets that I want to optimize so that they rebuild less often), or reusability (widgets that need to be reused with different Vms). Your example of using `state.authState.isLoggedIn` at the top of the widget tree is a great use case for `Vm`, as it minimizes unnecessary rebuilding of the top of the tree. For widgets deeper in the tree, accessing `context.state` and using `context.dispatch` directly is usually sufficient.

5. For `state.appState.appTheme`, while storing themes in Redux works, I recommend using my dedicated package, [Themed](https://pub.dev/packages/themed), for better theme management. For the same reason, don't store translations in Redux; use my dedicated package [i18n_extension](https://pub.dev/packages/i18n_extension). Finally, I also recommend using my [Fast Immutable Collections](https://pub.dev/packages/fast_immutable_collections) package to create your immutable State object (when they need immutable Lists, Sets and Maps). See https://pub.dev/publishers/glasberg.dev/packages for all my packages.

6. You mentioned, "Hope questions like these will get this library more attention on the search that it deserves." I may be biased but, I agree. I think AsyncRedux deserves more recognition due to its simplicity and power compared to alternatives like  `flutter_redux` or Bloc. It makes development much faster and the codebase a lot easier to understand than most state management solutions out there. Unfortunately, I’m clearly not great at marketing my packages.

**Comment by sofasurfa** [comment]
@marcglasberg 
Wow, thanks a swift answer back that's so full in useful details! **Happy New Year!** 

Yep, KISS sounds good 👍 Maybe renaming this Flutter package to KISS as well would make sense in the future? But probably keeping the word "Redux" in README so people can find it easier... 

1) How production ready is AsyncRedux for React compared to this package? +I think if we pick it for the web, we will be happy to contribute to it..
2) **Last question** just want to check if this is the right approach regarding StoreConnectors for each widget in list/edge: https://github.com/marcglasberg/async_redux/issues/166

**Comment by marcglasberg** [comment]
AsyncRedux/KISS for React is 100% production-ready. There is a complete TODO app example that you can run and edit at https://asyncredux.com/react/tutorial/persisting-the-state/. If you try to reimplement it in RTK, you'll find that the RTK version is much more complex and difficult to implement, modify, and understand. It's a good exercise to convince yourself and your team that AsyncRedux for React is the way to go.

In fact, AsyncRedux/KISS for React is, in some ways, better than AsyncRedux for Flutter. If any bugs are found, I will fix them quickly. Future contributions are welcome, of course!

I’m curious, what is your app/website about? (If it’s not a secret and you can share).

Please add me at https://x.com/GlasbergMarcelo so you don’t miss it when I launch KISS.

**Comment by sofasurfa** [comment]
@marcglasberg I agree that RTK isn't as simple as KISS, and I looking at the docs - you have convinced me to try to convince everyone to use it intead :) I sure will give you a follow on X. We are working on a location based selling plarform at the moment. And will start re-factoring from Blocs (accessed by service locators via get_it btw) to AsyncRedux, I should start calling it KISS by now as well :)
