### ISSUE TITLE
Better document how state is changed in async reducers, and creating code to test/demonstrate those.

### ISSUE THREAD

**Issue by marcglasberg** [marcglasberg/async_redux#31]

**Comment by marcglasberg** [comment]
https://github.com/marcglasberg/async_redux/blob/master/test/sync_async_test.dart

**Comment by bolein** [comment]
@marcglasberg did you actually delete the issue with the race discussion? I guess your repo should be an example of how to NOT do open-source

**Comment by marcglasberg** [comment]
@bolein You surely got an email with the content of that issue, and I suggest you read it. I welcome technical discussions and will never delete anything technical. However, the other guy in that thread got offended by the discussion, so I deleted it. I reserve the right not to keep the record of any personal conflicts in these issues, so as to keep this a safe space to all participants. But two important points: First, the complete answer to your original question in that thread is now part of the documentation (the README), so no information was lost there. And second, the potential problems raised by that person are addressed in this current issue. The tests were created to prove the correct behavior of the code, and the docs were improved with links and explanation. So, again, no information was lost.

**Comment by gadfly361** [comment]
@bolein I agree with you that all open-source discussions should be kept, even when they are unpleasant.  For example, I have kept [this exchange](https://github.com/gadfly361/soda-ash/issues/16) on one of my open-source repositories.

That said, I also believe that open-source discussions should be filled with constructive criticism.  

I truly think of open-source projects as a collective effort, and that _includes_ offering up differing opinions. Rather than saying that this repo is an example of how "NOT" to do open-source, maybe we should just say something regarding why we feel that discussions should be kept.

Most open-source authors (myself included) have something they can improve upon: could be documentation, readability of the code, test coverage, handling issues / PRs, etc. So I think it is our job, as community members, to help fill in whatever gaps we perceive there to be.  (As an aside, I think this repo is a good open-source example of documentation and readability of code 🤷‍♂)
