### ISSUE TITLE
Navigate actions do not support pushing and popping to get value from route

### ISSUE THREAD

**Issue by dalewking** [marcglasberg/async_redux#41]
First off I am skeptical that having redux know about the idea of Flutter navigation is a good idea, though I have created my own abstraction for it before but it feels dirty.

However if it is going to exist it should probably support the notion of pushing routes returning values via passing a value to pop. Not sure how that could be implemented. You have dispatchFuture which returns a Future<void> perhaps this can be extends to have async actions returning values and dispatchFuture return a Future<T>?

**Comment by dalewking** [comment]
Personally, I am going to explore using events to tell the UI to do the navigation, without the redux knowing anything about routes

**Comment by danim1130** [comment]
Just to chime in, I think that the way they implemented the current navigation (not in this library, but in Flutter) makes it hard to use when it's not for an simple example app. For example, when pushing a new page, it's not clear to me whether I should append it to the previous path (like /a/b), or just push it as a new root (like /b). The second one seems to be the recommended way, since we set the absolute path in routes, but if we want to restore the navigation stack on app startup, it is recommended to do it through the initialRoute property, which expects the path the first way. This is only made harder that right now, getting the current full path can only be accomplished through a hacky solution, and it also requires a context, which is not normally available inside Actions.

Right now, the NavigateAction is just a proxy action to the navigatorkey, it doesn't actually do anything with the store. Meanwhile, the navigation stack _feels_ like it should belong to the overall app state.

Also, I am personally not a fan of using pop as a way of returning values (unless it's from some kind of transient UI element, like dialogs). In my opinion, the app should be able to reconstruct itself purely from the app state even after process death, but returning a value with pop won't work after process death.

Ultimately, (IMO) the current navigation system is bad because of Flutter, and there's no great alternative to it. NavigateActions are the same as using a GlobalKey for navigation, and if we were to improve it, it should interact with the store in some way, making it easy to store and restore the navigation stack. This of course is a hard task, and it most likely would deserve it's own library.

**Comment by marcglasberg** [comment]
Yes, NavigateAction doesn't make Redux know about Flutter navigation. In the end it's really just a convenience to access GlobalKey for navigation. Maybe it would be nice if the store could contain the navigation stack, and maybe NavigateAction could accept an optional callback that gets a value from the popped route and puts it in the store. Problem is, with AsyncRedux I can only implement stuff I need for my own project, because I don't have knowledge outside of it. It's a large project, and it teaches me a lot, but I wouldn't know, for example, what else I should implement in NavigateAction. I only implemented what I needed and knew to be useful. There is also this plugin of mine: https://pub.dev/packages/back_button_interceptor which I think should be connected to routes is some way, but I'm really no sure how.

So if NavigateAction is to be improved in AsyncRedux, others must contribute to this repo.

**Comment by dalewking** [comment]
My point was that while there are valid arguments against the existence of navigate actions,  there really isn't a valid reason for it to only expose a subset of the navigation functionality and not include the ability to retrieve a value from a pushed route

**Comment by marcglasberg** [comment]
@dalewking Sure, I agree. What I'm saying is that I'll wait for contributions (PRs) to complete the navigation functionality.

**Comment by marcglasberg** [comment]
I guess this is fixed with the newer versions.
