### ISSUE TITLE
Making StoreConnector independent of BaseModel?

### ISSUE THREAD

**Issue by knaeckeKami** [marcglasberg/async_redux#6]
I began migrating my app to async_redux and so far, everything went fine.
However, I find one thing a bit annoying:
I already have ViewModels, and I used built_model to create them.
I cannot use these directly, as StoreConnector has a type Constraint to BaseModel.
`class StoreConnector<St, Model extends BaseModel>`
It seems that the only real reason for this is line 921 in store.dart:
`return widget.model.fromStore();`

This line would not compile without the type Constraint to BaseModel. 
However, this line performs an unsafe typecast anyway, as dart implicitly downcasts the BaseModel to the generic Model type, as showcased by this code snippet:

```
class ViewModelA extends BaseModel{
  @override
  BaseModel fromStore() {
    return ViewModelA();
  }

}

class ViewModelB extends BaseModel{
  @override
  BaseModel fromStore() {
    return ViewModelB();
  }
}

class MyWidget extends StatelessWidget {

  @override
    Widget build(BuildContext context) {
      return  StoreConnector<AppState, ViewModelA>(
        model: ViewModelB(),
        builder: (_,__) => Container());
}
}
```

This fails at runtime with the error message "type ViewModelB is not a subtype of ViewModelA".
This is unlikely to be a real issue, as it would get caught by the developer pretty easily, but I propose to make this cast explicit:
`return widget.model.fromStore() as Model;`.

This would also make it possible to remove the type constraint and I could use my already existing BuiltValue models.
I will open a pull request with this change shortly.

If you don't like this change, I can think of another solution:

- Implementing a CustomStoreConnector, that would pretty much the same as StoreConnector but doesn't use BaseModel. Trivial, but unnecessary code duplication imo.

**Comment by gadfly361** [comment]
@knaeckeKami I think there might be another reason BaseModel is being extended. See the line above, 920:

```
widget.model._setStore(widget.store);
```
If I understand correctly, I think that injects the store to the BaseModel which allows the ViewModel to access the `store`, `state`, and `dispatch` from some convenience getters.

**Comment by knaeckeKami** [comment]
`widget.model._setStore(widget.store);` still works, as widget.model is of the type BaseModel, not the generic Model type of StoreConnector.

It would still get called, and for my use case of using built_value object via the converter builder, it's not needed as I get the store passed in the converter function.

**Comment by gadfly361** [comment]
@knaeckeKami Thanks for the clarification, much appreciated!

**Comment by marcglasberg** [comment]
I will change this to allow for any type of ViewModel.

**Comment by marcglasberg** [comment]
So, a little more background on this: 

The `StoreConnector` actually accepts two parameters, of which one and only one must be provided: `model` or `converter`. The `converter` is the good old one from flutter_redux. It expects a static factory function that gets a `store` are returns a Model: `static ViewModel.from(store)`. 

@knaeckeKami have you tried using the `converter` or `model`? 

This was not mentioned in the docs because I don't use it, and frankly I then forgot about it. Otherwise I'd have created an example file for it, and would have tested.  I don't have my work computer with me now, so I can't test it, but it seems if I change BaseModel to Model it will work as intended for both `model` or `converter`.

Let me also explain why `model` and `BaseModel` may be useful instead of the `converter`. The idea was to (1) further reduce the Boilerplate by injecting state and dispatch yes, like @gadfly361 said, but more than that: (2) The BaseModel implements the Equatable trick to check changes to the ViewModel without using built_value, and (3) Once you have a class you can use its fields without having to pass them around. In the original static factory ViewModel you end up having a big single static method.

So for example, by using `BaseModel` you can do:

    ViewModel fromStore() => ViewModel.build(
		onIncrement: _onIncrement,
	  );
    
    VoidCallback _onIncrement: () => dispatch(IncrementAndGetDescriptionAction()),

With the original static factory you have to pass the `store` around:

    static ViewModel.fromStore() => ViewModel(
		onIncrement: _onIncrement(store),
	  );
    
    static VoidCallback _onIncrement(store) => () => store.dispatch(IncrementAndGetDescriptionAction()),

Besides all that, I have yet another two things to consider. First, I will try yet another design for the ViewModel which may be an improvement over what I've described above. But I'm not sure it's going to work yet. And also I'm talking to Remi Rousselet, and exploring a way to, maybe, let you be able to choose between the `StoreConnector` and `Provider` to connect the store to the widgets.

**Comment by knaeckeKami** [comment]
> @knaeckeKami have you tried using the `converter` or `model`?

I tried using the converter `approach`.

> but it seems if I change BaseModel to Model it will work as intended for both model or converter.

Yes, this would fix the edge case with the casting error at runtime as far as I can see.

I understand your concerns. I'm looking forward to possible improvements to BaseModel. 

I was trying to get something like [reselect](https://github.com/reduxjs/reselect)/ [re-frame subscriptions](https://github.com/Day8/re-frame/blob/master/docs/SubscriptionInfographic.md) working.

This is useful if calculating your ViewModels is expensive (Like sorting and filtering a big list...) The idea is to first extract some data from the state every time the state changes, compare this extracted data to the previously extracted data and only run the expensive calculation of the ViewModel if the extracted data changed. 

But my approach was flawed anyway, I'll probably write a custom StoreConnecter that supports this. If you're interested I can open a pull request once I'm finished. Or maybe it's better to provide this as a separate package (probably most people won't need this) if you'd like to keep this package slim.

**Comment by marcglasberg** [comment]
I don't think it's important to make the package slim. I want to make it easy to use. I would love to see your custom StoreConnector that supports reselect. I was, however, under the impression that this was added in the state. Just create a selector using the reselect lib. I don't understand what the StoreConnector has to do with it.

I was exploring a StoreConnector with much less boilerplate, that uses the built widget as the ViewModel, so it doesnt need a separate ViewModel class. This seems to work because Widgets are already templates. Have a look:

   https://gist.github.com/marcglasberg/ea2a91e4a3c9d15b6407788f168c77e2

**Comment by marcglasberg** [comment]
Do you use this? https://pub.dev/packages/reselect

**Comment by knaeckeKami** [comment]
Yes, it doesn't really make what I was trying to do. Wrong mindset, I need to adopt the redux mindset and get rid of the re-frame mindset :D.

I'll close this issue now. Thanks for the support.
